# -*- coding: utf-8 -*-
"""programming_fundamentals.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bNp1XEnPBnmUKfZ5wtMtEczfHuRaDMfP
"""

import networkx as nx
import matplotlib.pyplot as plt

# Initialize the graph
G = nx.Graph()

# Lines and stations with example distances (km)
lines = {
    "Western Line": {
        "stations": ["Churchgate", "Mumbai Central", "Dadar", "Bandra", "Andheri"],
        "distances": [2, 3, 2.5, 5]
    },
    "Central Line": {
        "stations": ["CSMT", "Byculla", "Dadar", "Kurla", "Thane"],
        "distances": [4, 2.5, 4.5, 10]
    },
    "Harbour Line": {
        "stations": ["Panvel", "Vashi", "Kurla", "Wadala", "CSMT"],
        "distances": [20, 8, 4, 6]
    },
    "Metro Line 1": {
        "stations": ["Versova", "DN Nagar", "Andheri", "Western Express Highway", "Ghatkopar"],
        "distances": [1.5, 2, 3, 2.5]
    },
    "Metro Line 2A": {
        "stations": ["Dahisar", "Borivali", "Malad", "Goregaon", "Andheri"],
        "distances": [4, 3, 2, 3]
    }
}

# Add nodes, edges, and distances for each line
for line, data in lines.items():
    stations = data["stations"]
    distances = data["distances"]
    for i, station in enumerate(stations):
        if G.has_node(station):
            G.nodes[station]["transfer"] = True
        else:
            G.add_node(station, line=line, transfer=False)
        if i > 0:
            G.add_edge(stations[i - 1], station, line=line, distance=distances[i - 1])

# Additional connections
G.add_edge("Dadar", "Andheri", distance=7)
G.add_edge("Dadar", "Kurla", distance=4)
G.add_edge("Andheri", "Ghatkopar", distance=3.5)
G.add_edge("Bandra", "Wadala", distance=6)

# Color map
color_map = {
    "Western Line": "green",
    "Central Line": "tan",
    "Harbour Line": "orange",
    "Metro Line 1": "teal",
    "Metro Line 2A": "olive"
}

plt.figure(figsize=(15, 10))
pos = nx.spring_layout(G, seed=42, k=0.2)

# Draw each line
for line, data in lines.items():
    stations = data["stations"]
    distances = data["distances"]
    station_nodes = [s for s in stations if not G.nodes[s]["transfer"]]
    nx.draw_networkx_nodes(G, pos, nodelist=station_nodes, node_color=color_map[line],
                           node_size=500, label=line)
    edge_labels = {(stations[i - 1], stations[i]): f"{distances[i - 1]} km"
                   for i in range(1, len(stations))}
    nx.draw_networkx_edges(G, pos,
                           edgelist=[(stations[i - 1], stations[i]) for i in range(1, len(stations))],
                           edge_color=color_map[line], width=2)
    nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels,
                                 font_color="black", font_size=10)

# Highlight transfer stations
transfer_stations = [s for s in G.nodes if G.nodes[s]["transfer"]]
nx.draw_networkx_nodes(G, pos, nodelist=transfer_stations, node_color="red",
                       node_size=800, edgecolors="black")

# Additional edges
additional_edges = [("Dadar", "Andheri"), ("Dadar", "Kurla"),
                    ("Andheri", "Ghatkopar"), ("Bandra", "Wadala")]
additional_edge_labels = {
    ("Dadar", "Andheri"): "7 km",
    ("Dadar", "Kurla"): "4 km",
    ("Andheri", "Ghatkopar"): "3.5 km",
    ("Bandra", "Wadala"): "6 km"
}
nx.draw_networkx_edges(G, pos, edgelist=additional_edges,
                       edge_color="gray", width=1, style="dashed")
nx.draw_networkx_edge_labels(G, pos, edge_labels=additional_edge_labels,
                             font_color="gray", font_size=10)

nx.draw_networkx_labels(G, pos, verticalalignment='top',
                        font_size=12, font_color="black")

# Legend
legend_elements = [
    plt.Line2D([0], [0], marker='s', color='w', label=line, markersize=12,
               markerfacecolor=color, linestyle="None")
    for line, color in color_map.items()
] + [
    plt.Line2D([0], [0], marker='s', color='w', label="Transfer Station", markersize=12,
               markerfacecolor="red", markeredgecolor="black", linestyle="None")
]

plt.title("Mumbai Transport Network with Estimated Distances")
plt.legend(handles=legend_elements, loc="upper left", frameon=False)
plt.show()